server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: microservice-vehicle
          uri: lb://microservice-vehicle:8081
          predicates:
            - Path=/reporte/**
        - id: microservice-registry
          uri: lb://microservice-registry:8082
          predicates:
            - Path=/registro/**
        - id: microservice-repair
          uri: lb://microservice-repair:8083
          predicates:
            - Path=/reparacion/**
        - id: microservice-reports
          uri: lb://microservice-reports:8084
          predicates:
            - Path=/reporte/**