server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registry-db
    username: postgres
    password: 12345678
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8791/eureka