apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-frontend-deployment
  labels:
    app: microservice-frontend-deployment
spec:
  selector:
    matchLabels:
      app: microservice-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-frontend-deployment
    spec:
      containers:
        - name: microservice-frontend
          image: arenasesteban/microservice-frontend
          ports:
            - containerPort: 3000c
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-frontend-service
  labels:
    app: microservice-frontend-service
spec:
  selector:
    app: microservice-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer