apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-reports-deployment
  labels:
    app: microservice-reports-deployment
spec:
  selector:
    matchLabels:
      app: microservice-reports-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-reports-deployment
    spec:
      containers:
        - name: microservice-reports
          image: arenasesteban/microservice-reports
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"