apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_REGISTRY: registry-db-service
  DB_PORT_REGISTRY: "5432"
  DB_NAME_REGISTRY: registry-db
  DB_HOST_REPAIR: repair-db-service
  DB_PORT_REPAIR: "5433"
  DB_NAME_REPAIR: repair-db
  DB_HOST_VEHICLE: vehicle-db-service
  DB_PORT_VEHICLE: "5434"
  DB_NAME_VEHICLE: vehicle-db