apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_REGISTRY: cG9zdGdyZXM=
  DB_PASSWORD_REGISTRY: MTIzNDU2Nzg=
  DB_USER_REPAIR: cG9zdGdyZXM=
  DB_PASSWORD_REPAIR: MTIzNDU2Nzg=
  DB_USER_VEHICLE: cG9zdGdyZXM=
  DB_PASSWORD_VEHICLE: MTIzNDU2Nzg=